server:
  port: 0

spring:
  application:
    name: scheduling-batch-spring-test

  data:
    redis:
      host: localhost
      port: 6379

  task:
    scheduling:
      pool:
        size: 2

zone-test:
  # 테스트할 시간 작성
  cron: "0 10 00 * * *"

logging:
  level:
    net.javacrumbs.shedlock: debug  # 락 획득/건너뜀 로그 확인용